---
title: "shelter-data"
author: "Heather Li"
date: "21/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(opendatatoronto)
library(lubridate)
```


```{r filtering-data, echo = FALSE}
#getting all the resources for the package, i.e. individual data sets
resources <- list_package_resources("8a6eceb2-821b-4961-a29d-758f3087732d")
#identify datastore resources; by default, Toronto Open Data sets datastore resource format to CSV for non-geospatial and GeoJSON for geospatial resources
datastore_resources <- filter(resources, tolower(format) %in% c('csv', 'geojson'))
#getting data for each year and cleaning it up
#2020
shelter_data_2020_overview <- datastore_resources %>% 
  filter(row_number()==5) %>% 
  get_resource() %>% 
  select(OCCUPANCY_DATE, SHELTER_POSTAL_CODE, OCCUPANCY, CAPACITY) %>% 
  filter(CAPACITY > 0) %>% 
  mutate(SHELTER_POSTAL_CODE = str_sub(SHELTER_POSTAL_CODE, 1, 3)) %>% 
  mutate(PERCENT_OCCUPIED = OCCUPANCY/CAPACITY) %>% 
  mutate(OCCUPANCY_DATE = mdy(OCCUPANCY_DATE)) %>%
  select(OCCUPANCY_DATE, SHELTER_POSTAL_CODE, PERCENT_OCCUPIED) %>% 
<<<<<<< HEAD
  group_by(OCCUPANCY_DATE) %>% 
=======
  group_by(SHELTER_POSTAL_CODE, OCCUPANCY_DATE) %>% 
>>>>>>> fc7f63dbe2a26506c807080f4073e3db03e7a78b
  summarize(AVG_ORATE = mean(PERCENT_OCCUPIED))
shelter_data_2020_overview
```

```{r plotting_the_data}
ggplot(data = shelter_data_2020_overview,
       mapping = aes(x = OCCUPANCY_DATE,
<<<<<<< HEAD
                     y = AVG_ORATE))+
=======
                     y = AVG_ORATE,
                     color = SHELTER_POSTAL_CODE))+
>>>>>>> fc7f63dbe2a26506c807080f4073e3db03e7a78b
  geom_line()+
  scale_y_continuous(labels = scales::percent_format(accuracy = 1))+
  labs(x = "Date",
       y = "Percent of Shelter Beds Occupied",
<<<<<<< HEAD
       color = "Postal Code",
       title = "A")+
  theme_minimal()
=======
       color = "Postal Code")
>>>>>>> fc7f63dbe2a26506c807080f4073e3db03e7a78b

```

